### PR TITLE
#6 Polling Status 

### PR DESCRIPTION
**Pull request by shidevil**
#6 Fetch every x second/minute

### CODE REVIEW

**Comment by metbosch** [comment]
The changes look nice and the comments in issue #6 leave positive feedback.
The only thing that I will add is dissable the fetch if the value in config.json is 0.

**Comment by shidevil** [comment]
Sure! No problem thank you!

**Comment by metbosch** [comment]
I just realized that this PR doesn't fix the issue #6 as we are not avoiding request when some ios device requests the state.
In any case, the PR should be merged as it adds a needed feature 😀

**Comment by shidevil** [comment]
@metbosch it doesn't fix the issue of #6? it is polling the value right? hahah care to elaborate? thank you :) still learning as well.

**Comment by shidevil** [comment]
@metbosch it doesn't avoid request but fetch in x minutes. So it's still polling status back to home kit right?

**Comment by shidevil** [comment]
i have reverted the commit. As i notice i was editing the wrong index.js repo! 

I have added disable fetch if refresh is 0

**Comment by metbosch** [comment]
@shidevil The issue #6 is about polling the status, you are right. But the user wants to avoid polling in the middle of the refresh period which is not implemented. And yes, after every fetch your code updates the homekit status.

**Comment by shidevil** [comment]
@metbosch the polling status will avoid poll in the middle of refresh period it will only poll every x/minus. Unless he opens the homekit app though. But that is HomeKit app function such that if you open the app it will refresh a new data. It's not a function that can be implemented if I'm not wrong.

**Comment by metbosch** [comment]
@shidevil 
I reviewed the code and I still see some problems. Mainly, the plugin will fail if the response time is larger than the refresh time.
We developed a similar functionality in a motion-sensor plugin. Therefore, if it is okay for you, I will try to apply the changes here and we can test them together.

**Comment by shidevil** [comment]
@metbosch 

Sure I will go and take a look at that.

**Comment by metbosch** [comment]
@shidevil 
Sorry for the late response :(
Can you take a look at develop branch (https://github.com/metbosch/homebridge-http-temperature/tree/develop)? It's working on my board and I implemented your changes using promises to avoid duplicated requests on slow devices.
Thanks!

**Comment by shidevil** [comment]
@metbosch will be taking a look at it and testing it.

**Comment by shidevil** [comment]
@metbosch i can confirm it is working. Good job. I have implemented your changes to my twine HTTP as well. It works good.

**Comment by metbosch** [comment]
Thanks @shidevil !!!
I will merge the changes into the master branch, increase the version and publish it to npm.
In addition, I'm closing this PR.

**Pull request closed without merging**
